In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [6]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-07-19 20:06:29,300] A new study created in memory with name: no-name-510e34a1-7942-4f81-8493-64bf61fa38be
[I 2025-07-19 20:06:29,718] Trial 0 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 128, 'max_depth': 4}. Best is trial 0 with value: 0.7616387337057727.
[I 2025-07-19 20:06:29,885] Trial 1 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 52, 'max_depth': 12}. Best is trial 0 with value: 0.7616387337057727.
[I 2025-07-19 20:06:30,182] Trial 2 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 99, 'max_depth': 11}. Best is trial 2 with value: 0.7635009310986964.
[I 2025-07-19 20:06:30,709] Trial 3 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 186, 'max_depth': 13}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-07-19 20:06:31,136] Trial 4 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 150, 'max_depth': 9}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-07-19 20:06:31,584] Trial 5 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 165, 'max_depth': 6}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-07-19 20:06:31,898] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 90, 'max_depth': 16}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-07-19 20:06:32,057] Trial 7 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 53, 'max_depth': 11}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-07-19 20:06:32,562] Trial 8 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 165, 'max_depth': 14}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-07-19 20:06:32,949] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 19}. Best is trial 3 with value: 0.7728119180633147.
[I 2025-07-19 20:06:33,480] Trial 10 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 197, 'max_depth': 20}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:34,046] Trial 11 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 200, 'max_depth': 19}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:34,603] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 20}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:35,098] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 182, 'max_depth': 17}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:35,643] Trial 14 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 199, 'max_depth': 18}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:36,098] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 169, 'max_depth': 15}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:36,369] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 97, 'max_depth': 20}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:36,872] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 185, 'max_depth': 17}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:37,283] Trial 18 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 149, 'max_depth': 9}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:37,624] Trial 19 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 111, 'max_depth': 18}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:37,846] Trial 20 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 20}. Best is trial 10 with value: 0.7783985102420856.
[I 2025-07-19 20:06:38,163] Trial 21 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 113, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:38,510] Trial 22 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 119, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:38,846] Trial 23 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 118, 'max_depth': 15}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:39,173] Trial 24 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 116, 'max_depth': 15}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:39,535] Trial 25 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 125, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:39,920] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 133, 'max_depth': 14}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:40,153] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 81, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:40,481] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 107, 'max_depth': 14}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:40,833] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 130, 'max_depth': 5}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:41,317] Trial 30 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 145, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:41,682] Trial 31 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 120, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:42,091] Trial 32 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 123, 'max_depth': 12}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:42,421] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:42,808] Trial 34 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 127, 'max_depth': 15}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:43,039] Trial 35 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 97, 'max_depth': 3}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:43,432] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 138, 'max_depth': 13}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:43,756] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 13}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:43,980] Trial 38 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 78, 'max_depth': 10}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:44,414] Trial 39 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 158, 'max_depth': 17}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:44,601] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 67, 'max_depth': 7}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:44,916] Trial 41 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 111, 'max_depth': 19}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:45,294] Trial 42 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 18}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:45,649] Trial 43 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 126, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:45,944] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 102, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:46,306] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 128, 'max_depth': 14}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:46,629] Trial 46 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 115, 'max_depth': 16}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:47,032] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 15}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:47,278] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 87, 'max_depth': 12}. Best is trial 21 with value: 0.7802607076350093.
[I 2025-07-19 20:06:47,538] Trial 49 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 21 with value: 0.7802607076350093.

In [7]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 113, 'max_depth': 18}

In [8]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

Samplers in Optuna

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [10]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-07-19 20:08:33,800] A new study created in memory with name: no-name-b660719c-7f1e-4cdf-b186-c22729e98bdc
[I 2025-07-19 20:08:34,358] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 158, 'max_depth': 16}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-07-19 20:08:34,594] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 54, 'max_depth': 12}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-07-19 20:08:34,988] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 78, 'max_depth': 6}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-07-19 20:08:35,509] Trial 3 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 83, 'max_depth': 8}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-07-19 20:08:35,823] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 82, 'max_depth': 15}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-07-19 20:08:36,193] Trial 5 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 90, 'max_depth': 7}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-07-19 20:08:36,908] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 197, 'max_depth': 15}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:37,372] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 92, 'max_depth': 11}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:37,596] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 67, 'max_depth': 9}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:38,014] Trial 9 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 124, 'max_depth': 11}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:38,281] Trial 10 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 81, 'max_depth': 10}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:38,525] Trial 11 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 65, 'max_depth': 12}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:38,970] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 133, 'max_depth': 8}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:39,552] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 187, 'max_depth': 19}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:39,779] Trial 14 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 75, 'max_depth': 6}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:40,034] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 68, 'max_depth': 15}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:40,438] Trial 16 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 126, 'max_depth': 11}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:40,778] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 127, 'max_depth': 5}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:41,190] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 15}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:41,776] Trial 19 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 191, 'max_depth': 5}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:42,562] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 160, 'max_depth': 17}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:43,116] Trial 21 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 172, 'max_depth': 10}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-07-19 20:08:43,371] Trial 22 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 20}. Best is trial 22 with value: 0.7765363128491621.
[I 2025-07-19 20:08:43,564] Trial 23 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 66, 'max_depth': 13}. Best is trial 22 with value: 0.7765363128491621.
[I 2025-07-19 20:08:44,098] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 197, 'max_depth': 10}. Best is trial 22 with value: 0.7765363128491621.
[I 2025-07-19 20:08:44,417] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 115, 'max_depth': 12}. Best is trial 22 with value: 0.7765363128491621.
[I 2025-07-19 20:08:44,850] Trial 26 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 7}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:45,319] Trial 27 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 172, 'max_depth': 19}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:45,634] Trial 28 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 92, 'max_depth': 10}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:45,943] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 112, 'max_depth': 7}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:46,474] Trial 30 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 193, 'max_depth': 17}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:46,967] Trial 31 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 192, 'max_depth': 7}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:47,217] Trial 32 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 91, 'max_depth': 7}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:47,577] Trial 33 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 118, 'max_depth': 10}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:48,003] Trial 34 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 174, 'max_depth': 3}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:48,552] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 196, 'max_depth': 8}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:48,744] Trial 36 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 77, 'max_depth': 6}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:48,995] Trial 37 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 94, 'max_depth': 4}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:49,154] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 58, 'max_depth': 16}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:49,428] Trial 39 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 68, 'max_depth': 12}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:49,609] Trial 40 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 74, 'max_depth': 3}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:50,142] Trial 41 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 188, 'max_depth': 14}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:50,645] Trial 42 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 177, 'max_depth': 3}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:50,852] Trial 43 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 69, 'max_depth': 17}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:51,218] Trial 44 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 120, 'max_depth': 19}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:51,447] Trial 45 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 18}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:52,047] Trial 46 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 173, 'max_depth': 6}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:52,475] Trial 47 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 135, 'max_depth': 3}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:53,180] Trial 48 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 196, 'max_depth': 20}. Best is trial 26 with value: 0.7802607076350093.
[I 2025-07-19 20:08:53,352] Trial 49 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 61, 'max_depth': 14}. Best is trial 26 with value: 0.7802607076350093.

In [11]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 129, 'max_depth': 7}

In [12]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [13]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [14]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-07-19 20:10:20,364] A new study created in memory with name: no-name-fa37a2d2-7cd3-4a48-887a-845f44f0363c
[I 2025-07-19 20:10:20,622] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-07-19 20:10:21,089] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-07-19 20:10:21,233] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:21,520] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:21,794] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:21,934] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:22,304] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:22,740] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:23,136] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:23,794] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:24,346] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:24,895] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:25,391] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-19 20:10:25,526] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-07-19 20:10:25,797] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-07-19 20:10:25,933] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [15]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

Optuna Visualizations

In [17]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [18]:
# 1. Optimization History
plot_optimization_history(study).show()

In [19]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [20]:
# 3. Slice Plot
plot_slice(study).show()

In [21]:
# 4. Contour Plot
plot_contour(study).show()

In [22]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

Optimizing Multiple ML Models

In [23]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [24]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [25]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-07-19 20:14:04,881] A new study created in memory with name: no-name-2552d992-2b2c-41bd-abc5-3299180b6863
[I 2025-07-19 20:14:05,392] Trial 0 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 149, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.7653631284916201.
[I 2025-07-19 20:14:05,424] Trial 1 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 23.709130135842457, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 0 with value: 0.7653631284916201.
[I 2025-07-19 20:14:05,441] Trial 2 finished with value: 0.7243947858472998 and parameters: {'classifier': 'SVM', 'C': 1.5771526664334863, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7653631284916201.
[I 2025-07-19 20:14:05,463] Trial 3 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 1.7236294160508674, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:05,485] Trial 4 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 5.321884243532023, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:05,503] Trial 5 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 0.828860745197348, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:05,526] Trial 6 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.7762473099610715, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:05,542] Trial 7 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 2.0251629905002746, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:06,233] Trial 8 finished with value: 0.7597765363128491 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 256, 'learning_rate': 0.07122738997053038, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:06,795] Trial 9 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 243, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:07,107] Trial 10 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 55, 'learning_rate': 0.010429332842641574, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:07,133] Trial 11 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 0.13704940505919253, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7690875232774674.
[I 2025-07-19 20:14:07,150] Trial 12 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.30168351540773614, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137803.
[I 2025-07-19 20:14:07,336] Trial 13 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 62, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 12 with value: 0.7858472998137803.
[I 2025-07-19 20:14:07,351] Trial 14 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12206101919993373, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:08,327] Trial 15 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 163, 'learning_rate': 0.29964756682275334, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:08,353] Trial 16 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1324417575847145, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:08,376] Trial 17 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10607535779873074, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:10,668] Trial 18 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 296, 'learning_rate': 0.013329854870847516, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:10,938] Trial 19 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 106, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:10,956] Trial 20 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.33217253811200387, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:10,973] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10873919595006182, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:10,990] Trial 22 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2510017499121998, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:11,006] Trial 23 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10383455744903175, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:11,131] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 61.54586073965214, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:11,146] Trial 25 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4045149377367993, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:11,165] Trial 26 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.1750510375749254, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:11,207] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 10.257632819891061, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:12,536] Trial 28 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 212, 'learning_rate': 0.2950835972739684, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:12,895] Trial 29 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 120, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,564] Trial 30 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 202, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,581] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10302345018540998, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,603] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19104312448704844, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,625] Trial 33 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5954042339319972, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,643] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10644721258782143, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,660] Trial 35 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21102175103656637, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,682] Trial 36 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.47443141628568064, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,702] Trial 37 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.19706600929932183, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,720] Trial 38 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.18162719867617622, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,735] Trial 39 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.11017415757330673, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,751] Trial 40 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.31657487878012314, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,767] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10224972235638485, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,785] Trial 42 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14590477894032403, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,800] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17401998334256738, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,815] Trial 44 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15760785167992136, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:13,833] Trial 45 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 1.198782202254366, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:15,506] Trial 46 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 295, 'learning_rate': 0.04466840987172039, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:15,525] Trial 47 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.27511747534313, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:15,831] Trial 48 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 102, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:15,858] Trial 49 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.3252362756448175, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,729] Trial 50 finished with value: 0.7169459962756052 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 194, 'learning_rate': 0.07109066477225864, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,750] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.139688674427402, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,770] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14378134911224666, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,793] Trial 53 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.1537323190791657, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,813] Trial 54 finished with value: 0.7411545623836128 and parameters: {'classifier': 'SVM', 'C': 0.4962475349666867, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,832] Trial 55 finished with value: 0.7616387337057727 and parameters: {'classifier': 'SVM', 'C': 0.2453781205980986, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,848] Trial 56 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14104497091239684, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,869] Trial 57 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.7856621903391914, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:18,905] Trial 58 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.887790337121382, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:19,582] Trial 59 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 263, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:19,598] Trial 60 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3739817906359126, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:19,614] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13339272259903798, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:19,655] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1295316797073308, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:19,684] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14094343608398388, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:19,701] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24759747486406405, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:19,722] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14102324191904106, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,630] Trial 66 finished with value: 0.7597765363128492 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 144, 'learning_rate': 0.026381171038755917, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 8}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,647] Trial 67 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.239381357212996, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,676] Trial 68 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 29.226592240580857, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,694] Trial 69 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.33931047930363256, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,890] Trial 70 finished with value: 0.7839851024208566 and parameters: {'classifier': 'RandomForest', 'n_estimators': 75, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,913] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14750117787639686, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,928] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12581200616663946, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,943] Trial 73 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12961176466082205, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,960] Trial 74 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2112179807788039, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,975] Trial 75 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1750884348156574, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:20,995] Trial 76 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.14062980306167708, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:21,010] Trial 77 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10082587166624515, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:21,031] Trial 78 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.1960378157626512, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:21,047] Trial 79 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 0.22721581979522162, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:22,335] Trial 80 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 224, 'learning_rate': 0.143651752827889, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.7895716945996275.
[I 2025-07-19 20:14:22,349] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13209870357764725, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7895716945996275.

In [26]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12206101919993373, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [27]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.765363,2025-07-19 20:14:04.886937,2025-07-19 20:14:05.392357,0 days 00:00:00.505420,NaN,True,RandomForest,NaN,NaN,NaN,4.0,3.0,5.0,149.0,COMPLETE
1,1,0.737430,2025-07-19 20:14:05.393279,2025-07-19 20:14:05.424801,0 days 00:00:00.031522,23.709130,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,0.724395,2025-07-19 20:14:05.425767,2025-07-19 20:14:05.441777,0 days 00:00:00.016010,1.577153,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.769088,2025-07-19 20:14:05.442685,2025-07-19 20:14:05.463804,0 days 00:00:00.021119,1.723629,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.756052,2025-07-19 20:14:05.464702,2025-07-19 20:14:05.485440,0 days 00:00:00.020738,5.321884,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.689013,2025-07-19 20:14:23.088749,2025-07-19 20:14:23.105337,0 days 00:00:00.016588,99.295283,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.785847,2025-07-19 20:14:23.105944,2025-07-19 20:14:23.123270,0 days 00:00:00.017326,0.199232,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.756052,2025-07-19 20:14:23.124014,2025-07-19 20:14:23.150254,0 days 00:00:00.026240,0.157837,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.765363,2025-07-19 20:14:23.150971,2025-07-19 20:14:23.656917,0 days 00:00:00.505946,NaN,NaN,GradientBoosting,NaN,NaN,0.023297,19.0,8.0,3.0,85.0,COMPLETE
99,99,0.789572,2025-07-19 20:14:23.657780,2025-07-19 20:14:23.673708,0 days 00:00:00.015928,0.116185,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [28]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 80
RandomForest        10
GradientBoosting    10
Name: count, dtype: int64

In [29]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.747114
RandomForest        0.764804
SVM                 0.776234
Name: value, dtype: float64

In [30]:
# 1. Optimization History
plot_optimization_history(study).show()

In [31]:
# 3. Slice Plot
plot_slice(study).show()

In [32]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [ ]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")